[workspace]
members = ["ch9329", "ch9329-serialport"]
resolver = "3"

[workspace.dependencies]
anyhow = "1.0.95"
serialport = "4.7.0"
thiserror = "2.0.11"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
