[workspace]
members = ["ch9329", "ch9329-copy", "ch9329-serialport"]
resolver = "3"

[workspace.dependencies]
anyhow = "1.0.99"
bitflags = "2.9.2"
clap = "4.5.45"
serialport = "4.7.2"
thiserror = "2.0.15"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
