[package]
name = "ch9329-serialport"
version = "0.1.0"
edition = "2024"

[dependencies]
ch9329.path = "../ch9329"
serialport.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
anyhow.workspace = true
tracing-subscriber.workspace = true
